apiVersion: v1
kind: Pod
metadata:
  name: nvidia-example-pod
spec:
  containers:
  - name: nvidia-container
    image: hank997/webapp:v1
    resources:
      requests:
        cpu: 1
        nvidia.com/gpu: 1
        memory: 256Mi
      limits:
        cpu: 1
        nvidia.com/gpu: 1
        memory: 256Mi
