apiVersion: v1
kind: Pod
metadata:
  name: webapp01
  labels:
    app: web
    env: prd
spec:
  volumes:
  - name: test-code
    emptyDir: {}
  initContainers:
  - name: move-code
    image: hank997/webapp:v2
    command: ["sh", "-c", "mv /var/www/index.html /home/data/"]
    volumeMounts:
    - name: test-code
      mountPath: /home/data/
  containers:
  - name: webapp
    image: hank997/webapp:v1
    volumeMounts:
    - name: test-code
      mountPath: /home/data/
