apiVersion: v1
kind: PersistentVolume
metadata:
  name: hank-jenkins
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /data/hank-jenkins

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hank-jenkins
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  containers:
  - name: device-container
    image: hank997/webapp:v1
    volumeMounts:
    - name: test-deivce
      mountPath: /data
  volumes:
  - name: test-deivce
    persistentVolumeClaim:
      claimName: hank-jenkins
