apiVersion: v1
kind: PersistentVolume
metadata:
  name: hank-jenkins
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /data/hank-jenkins

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hank-jenkins
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
