apiVersion: v1
kind: PersistentVolume
metadata:
  name: das-passwd
  labels:
    name: das-passwd
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /data/das-data/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 10.10.10.5
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: das-passwd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      name: das-passwd
