apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-chartmuseum
  labels:
    name: harbor-chartmuseum
spec:
  local:
    path: /data/harbor/chartmuseum
    fsType: xfs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s01.example.yaml
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 50Gi
