apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-redis
  labels:
    name: harbor-redis
spec:
  local:
    path: /data/harbor/redis
    fsType: xfs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s01.example.com
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
