apiVersion: apps/v1
kind: Deployment
metadata:
  name: hankbook
  labels:
    name: hankbook
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      name: hankbook
      app: web
  template:
    metadata:
      labels:
        name: hankbook
        app: web
    spec:
      containers:
      - name: hankbook
        image: hank997/hankbook:v1

---
apiVersion: v1
kind: Service
metadata:
  name: hankbook-service
  labels:
    name: hankbook-service
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: sshd
      nodePort: 30088
  selector:
    app: hankbook
